### ISSUE TITLE
style volume component

### ISSUE THREAD

**Issue by guilhermeabell** [guilhermeabell/spotify-webapp#13]

**Comment by alangabrielbs** [comment]
**Default**
<img width="131" alt="image" src="https://user-images.githubusercontent.com/48570772/197608200-ecc70b5a-b1e5-403d-bb52-dbc0f21f8a3b.png">

**Hover**
<img width="137" alt="image" src="https://user-images.githubusercontent.com/48570772/197608238-7ea6ead9-f3a3-4d6a-ac5a-7fdc841de2ca.png">

**Muted**
<img width="130" alt="image" src="https://user-images.githubusercontent.com/48570772/197608291-f9ba54b2-c400-423c-9b97-2da21b1b0b47.png">
